{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "smart-local-provisioner.fullname" . }}
  labels:
{{ include "smart-local-provisioner.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "smart-local-provisioner.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "smart-local-provisioner.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
