apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-local-provisioner
  namespace: local-path-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-local-provisioner
  template:
    metadata:
      labels:
        app: smart-local-provisioner
    spec:
      serviceAccountName: smart-local-provisioner-service-account
      containers:
        - name: smart-local-provisioner
          image: lizhongxuan/smart-local-provisioner:master-head
          imagePullPolicy: Always
          command:
            - smart-local-provisioner
            - --debug
            - start
            - --config
            - /etc/config/config.json
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: config-volume
          configMap:
            name: local-path-config
